// src/app/layout.tsx
import type { Metadata } from 'next'
import { ClerkProvider, SignedIn, SignedOut } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header />

          <SignedIn>{children}</SignedIn>

          <SignedOut>
            <div className="flex items-center justify-center h-[80vh]">
              <p className="text-xl font-semibold">로그인을 해주세요.</p>
            </div>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  )
}
